Fixes #31227 - Add index page in React
theforeman/foreman_webhooks pull request #12
Opened 2020-11-01 20:09 UTC by ofedoren

2020-11-02 16:41 UTC, lzap commented
@ofedoren I think you need to get someone with JS/React knowledge for the review. :-) I can perform testing when needed tho.

2020-11-03 13:30 UTC, laviro commented
Nice work @ofedoren !
any chance you could split this PR into a smaller one that just adds the React infrastructure?
and then rebase this PR which will contain only the `Webpack\ForemanWebhooks` folder

2020-11-03 15:04 UTC, MariaAga requested changes
I did a quick overview before  the split and noticed a few things:

2020-11-04 16:46 UTC, ofedoren commented
Thanks, @laviro, @MariaAga!

I've changed this PR to be the small one, I'll create another one for index page.

2020-11-05 08:25 UTC, laviro commented on .eslintignore
> +!webpack/**/*.js
I guess you just want to avoid the assets js files?
I think you can instead ignore what's in the `app` folder:

```suggestion
app/**
```

2020-11-05 08:25 UTC, laviro commented on package.json
> +  "version": "1.0.0",
can you match the version in https://github.com/theforeman/foreman_webhooks/blob/master/lib/foreman_webhooks/version.rb#L4

```suggestion
  "version": "0.0.1",
```

2020-11-05 08:25 UTC, laviro commented on package.json
> +  "description": "Foreman Webhooks",
```suggestion
  "description": "This plugins allows to configure Webhooks for Foreman.",
```

2020-11-05 08:25 UTC, laviro commented on package.json
> +    "@theforeman/vendor": ">= 4.2.1"
can you update all `theforeman` packages to the latest version of: `4.15.1` ?

2020-11-05 08:25 UTC, laviro commented on package.json
> +  }
can be removed for now

2020-11-05 08:25 UTC, laviro commented on package.json
> +    "raf": "^3.4.0",
also, I don't think you need `raf`

2020-11-05 09:02 UTC, laviro reviewed
can you also add an experimental "Hello world" route in this PR?
so we could test that the React part actually works

I created a small commit you can use: https://github.com/theforeman/foreman_webhooks/pull/14/commits/a9f73b47f25e2891f7976b058c80e9cee55d1b17 (accidentally pushed it to the upstream)

2020-11-05 11:52 UTC, ofedoren commented
Thanks, @laviro! I've applied suggested changes and cherry-pick your commit. Although I think it's better to squash those.

2020-11-09 12:39 UTC, laviro reviewed
Thanks @ofedoren !
sure, go ahead and squash the commits :+1:

2020-11-09 13:43 UTC, ofedoren commented
@laviro, done :)

2020-11-09 15:08 UTC, laviro approved these changes
Thanks!! LGTM

2020-11-12 12:45 UTC, ofedoren commented
@lzap, can we get this merged if you don't any other concerns?

2020-11-30 13:45 UTC, lzap commented
I meerged the other PR #13 , this can now be closed.

2020-11-30 13:45 UTC, closed without merging