Fixes #32134 - client certificate support for smart proxy
theforeman/foreman_webhooks pull request #32
Opened 2021-03-23 16:04 UTC by lzap

This allows running webhooks over HTTPS against smart proxies running shellhooks.

2021-03-24 18:46 UTC, ofedoren requested changes
Thanks, @lzap! LGTM, but I have just one thing to ask, see inline.

2021-03-25 08:57 UTC, lzap commented on app/controllers/concerns/foreman_webhooks/controller/parameters/webhook.rb
> +                            :proxy_authorization
Done.

2021-03-26 15:12 UTC, ofedoren reviewed
Thanks, @lzap. LGTM and seems to be working, although just one nipick, please see inline.

2021-03-26 16:20 UTC, lzap commented on app/controllers/api/v2/webhooks_controller.rb
> +          param :proxy_authorization, String, N_('Authorize with Foreman client certificate and validate smart-proxy CA from Settings')
Fixed good catch.

2021-03-26 17:13 UTC, ofedoren approved these changes
Thanks, @lzap! Merging.

2021-03-26 17:14 UTC, merged

2021-03-29 07:10 UTC, lzap commented
Thanks right on time!