Fixes #35385 - Prevent auto-reset of password while editing
theforeman/foreman_webhooks pull request #54
Opened 2022-08-22 17:21 UTC by ofedoren

2022-08-25 17:19 UTC, MariaAga requested changes
Looks good, left one comment. There is a bug that if a user clicks on "change the password" icon, closes the modal (without saving) and opens it again (with the same or different webhook) the password is editable. 
I would set the value to false in the `onClose` function for the modal or something

2022-09-01 14:51 UTC, ofedoren commented
Thanks, @MariaAga, updated. Should work now, but due to some limitations and just to not make a PR to the core, I needed to force users to use the buttons only to close the modal. Thus I've removed `x` mark in the header.

2022-09-02 08:57 UTC, MariaAga commented on webpack/ForemanWebhooks/Routes/Webhooks/Components/WebhookForm/Components/ForemanFormikField.js
> +                  href="#"
@ofedoren any reasons for keeping it an `a` tag and not changing to button?

2022-09-02 08:57 UTC, MariaAga commented
Yup, works well now!

2022-09-02 10:54 UTC, ofedoren commented on webpack/ForemanWebhooks/Routes/Webhooks/Components/WebhookForm/Components/ForemanFormikField.js
> +                  href="#"
@MariaAga, my bad, forgot to change.

2022-09-02 10:54 UTC, ofedoren commented
Updated with button instead of link.

2022-09-02 13:41 UTC, MariaAga approved these changes
lgtm!

2022-09-05 12:05 UTC, ofedoren commented
Thanks, @MariaAga! Merging then :)

2022-09-05 12:05 UTC, merged